---
title: "HW #8: R Lab - Repeated Measures ANOVA"
format: live-html
resources:
  - data
webr:
  packages:
    - dplyr 
    - tidyr
    - ggplot2
    - rstatix
toc: true
engine: knitr

---

{{< include /_extensions/r-wasm/live/_knitr.qmd >}}

## R Lab #4 

Welcome to the fourth R Lab for PSYS 2012!

This lab, and the remainder of the labs this semester, will focus more on interpreting output of R analyses and practicing writing professional, APA style reports. The R code exercises will guide you through how to collect descriptive statistics and conduct t-tests. I will do the analyses for you, so you only need to click "Run Code" to get the output. For the homework, you will create a formal report, including a graph of the results and a formal APA style write up as we have practiced in class.  

If you are interested in learning more about how to do analyses in R on your own, I recommend the following resources: 

- [Learning Statistics with R by Danielle Navarro](https://learningstatisticswithr.com/book/)
- [R for Data Science by Hadley Wickham](https://r4ds.hadley.nz/)

::: {.callout-tip title="Remember: Questions will appear like this!"}
As a reminder, throughout this lab questions that you need to answer will appear in a block like this! 

**You will write the answers to all questions in a *separate* word document!**

All questions will include a rubric so you know what information to include.

*Rubric example:*

-   This is not a real rubric but is what a rubric will look like! 
:::

Type your answers to these questions in a separate word document and upload that document to Brightspace for evaluation. There is an "answer template" document attached to the Brightspace assignment.

## Replication of Craik & Tulving (1975)

In the last R lab, we used an independent measures t-test to replicate a classic cognitive psychology study showing that processing "deep" features of a word (like the meaning) aids in the later recall of a word, compared to processing the "shallow" features of a word (like what letters it contains). 

In class we collected data from a study by Craik & Tulving that replicated and extended these findings in 1975, exploring in more detail what features of a word lead to "deep" processing versus "shallow" processing. In this demonstration, you were asked to process whether a word was written in upper-case or lower-case letters (the `case` condition), whether it rhymed with another word (the `rhyme` condition), or whether it fit into a sentence (the `sentence` condition). This was a within groups design (all participants completed all three types of trials) so we will conduct a repeated-measures ANOVA to determine which type of processing leads to the best retention. 

The citation for the original paper is:
Craik, F. I., & Tulving, E. (1975). Depth of processing and the retention of words in episodic memory. Journal of experimental Psychology: General, 104(3), 268.

Let's see if we replicate these findings with our class data. I'll provide the R code to you (and explain it) so you just need to click "Run Code" to get the analysis. Once you have done all three tasks, you will write an APA style report of the analyses you've done. 

### Exploring our data

To start, let's load in the data. Remember that what you see as output here is just a glimpse of the first six rows of data. 


```{webr}
#| edit: false
craik <- read.csv("data/craik.csv") |>
    pivot_longer(cols = !ID, 
               names_to = "condition", 
               values_to = "score") 

head(craik)
``` 

You can see that we have three variables, `id`, which is just an ID number assigned to each participant, `condition`, which identifies the type of trial (`case`, `rhyme`, or `word`), and `score`, which tells us how many words of that trial time participants remembered. Note that because this is a within groups design, each participant ID has three rows in the dataset (one for each score they received). 

Click "Run Code" below to create a bar graph of the data with errorbars showing 95% CI. 

Before we move on, take a second to understand the story that this graph is telling you. Based on this graph, what do you expect our descriptive statistics to look like? What do you expect the results of our hypothesis test to be?

```{webr}
ggplot(data = craik, aes(x = condition, y = score)) + 
       geom_bar(stat = "summary", fun="mean") + 
       geom_errorbar(stat="summary", fun.data="mean_se", fun.args = list(mult = 1.96), width=0) + 
  theme_classic() 
```

Let's also get descriptive statistics for each group: 

```{webr}
craik |>
  group_by(condition) |>
  summarize(mean = mean(score), 
            sd = sd(score))
```

### Within groups ANOVA in R

Now that we've seen the data, let's run the ANOVA and see if there is a significant effect of condition on the number of words remembered. 

There are many ways to conduct an ANOVA in R. In the code block below, first I 

I'll be using the function `anova_test()` from the `rstatix` package, which is a popular tool to use to conduct ANOVA. 

The ANOVA table that it produces contains less information than the complete ANOVA table that I showed you in class, but it contains all of the information that you need to produce an APA style write-up of the results of an ANOVA. If you want to know more about how to do an ANOVA yourself, you can read the comments in the code block below, or you can just click "Run Code" to see the results: 

```{webr}
# anova_test() from the rstatix package
# to conduct a within-groups ANOVA you need to provide the following aruguments:
# data = identifies the dataframe you are using
# dv = identifies the dependent variable ("score" here)
# wid = identifies the variable that identifies participants ("ID" here)
# within = identifies the within-group variable ("condition" here)
craik_anova <- anova_test(data = craik, dv = "score", wid = "ID", within = "condition")

# Use the function get_anova_table() to see the results of the anova
get_anova_table(craik_anova)
```

If you look at the output of the code block above, you will see everything you need to write up an ANOVA in APA format. `DFn` stands for "degrees of freedom in numerator", also known as "df between". `DFd` stands for "degrees of freedom in denominator", or "df within". You might notice that these are decimals (not whole numbers like we calculated in class)! That's because in this example Mauchley's test of sphericity (one of the assumptions of a within groups ANOVA) is significant, meaning the assumption of sphericity is not met, so R has applied a correction to the degrees of freedom to account for this. If you want, you can type "craik_anova" at the bottom of the code block above, and click "run code" again to see Mauchley's test and the correction that has bee applied (this is not necessary for completing the homework though!). 

After `DFn` and `DFd`, R reports the F-ratio and the p-value. Remember, p-values presented using scientific notation indicate very small p-values (p < .001). The anova table here also helps you out by telling you if it is significant at alpha of .05! If there is an asterisk below `p<.05`, that means the result is significant. Finally, the table reports `ges`, which is generalized eta-squared, our measure of effect size for ANOVA. 

### Post-hoc testing

Remember, the ANOVA only tests the *omnibus null hypothesis* that there is no difference between groups. If we reject the null, we just know that there is some difference, but we don't know specifically which conditions differ from one another. Post-hoc testing allows us to identify which means are different in an ANOVA.

Post-hoc testing is complex for a repeated measures ANOVA (especially when the assumption of sphericity is not met, as it is not in this example, which makes the TukeyHSD test inappropriate). We will use the simplest post-hoc test here, the Bonferroni correction. As a reminder, for the Bonferroni correction, we adjust our alpha level to account for multiple tests. In this example, we have three conditions, and therefore three possible pairwise tests we might want to run: 

- `case` vs. `rhyme` condition
- `rhyme` vs. `sentence` condition
- `case` vs. `sentence` condition

If our original alpha = .05, with the Bonferroni correction our *new* alpha level will be $.05 / 3 = .0167$. 

In the code block below I have conducted three paired t-tests, one for each comparison. Identify which comparisons are significant by comparing the p-value generated by the t-test **to the Bonferroni corrected alpha level of .0167**!

```{webr}
craik_posthoc <- read.csv("data/craik.csv")

t.test(craik_posthoc$case, craik_posthoc$rhyme, paired = T)
t.test(craik_posthoc$rhyme, craik_posthoc$sentence, paired = T)
t.test(craik_posthoc$case, craik_posthoc$sentence, paired = T)
```

### Homework rubric

See below for the rubric for this homework, which asks you to *both* present the graph created above *and* write up the results of the ANOVA & post-hoc testing. Review notes from class for how to report these in APA format!

::: {.callout-tip title="Question 1: Writing up results of within-groups ANOVA"}

Use all of the R output from the code blocks above to write a formal APA style write up (**including a graph of the findings!**). See rubric below to make sure you are including everything you need to include! You should be able to include all of this information in just a few (1-3) sentences. **Your write-up should be written as a single paragraph, not as separate answers to each of the bullet points below**. 


*Rubric for Question 1 (10 points total):*

- **1 point** Plot is included and is legible & professional (not a screenshot or photo of your entire computer screen) 
- **1 point** Identify the type of ANOVA conducted 
- **1 point** State (briefly) what was measured/what the conditions were.
- **1 point** Identify whether the difference found in the initial ANOVA was significant. Make sure when interpreting the initial ANOVA, you only state that the effect of the condition was significant (don't make any claims about any specific differences in means!)
- **2 points** Report the results of the initial ANOVA by reporting the following statistics **in APA format**: F, both dfs, p, and generalized eta-squared, rounding all values to 2 decimal places. Review slides/notes from class if you are not sure how to report these in APA format!
- **3 points** Report the results of post-hoc testing: State what type of post-hoc test we conducted, and then report means & sd *only* for significant comparisons, as well as the p-value for the significant post-hoc comparisons. Review slides/notes from class if you are not sure how to report these in APA format!
- **1 point** Your report must be presented in a single, professional short paragraph (2-4 sentences). Proofread for grammatical & spelling errors

:::