---
title: "HW #11: R Lab - Regression"
format: live-html
resources:
  - data
webr:
  packages:
    - dplyr 
    - tidyr
    - ggplot2
    - GGally
toc: true
engine: knitr

---

{{< include /_extensions/r-wasm/live/_knitr.qmd >}}

## R Lab #6

Welcome to the sixth and final R Lab for PSYS 2012!

If you are interested in learning more about how to do analyses in R on your own, I recommend the following resources: 

- [Learning Statistics with R by Danielle Navarro](https://learningstatisticswithr.com/book/)
- [R for Data Science by Hadley Wickham](https://r4ds.hadley.nz/)

::: {.callout-tip title="Remember: Questions will appear like this!"}
As a reminder, throughout this lab questions that you need to answer will appear in a block like this! 

**You will write the answers to all questions in a *separate* word document!**

All questions will include a rubric so you know what information to include.

*Rubric example:*

-   This is not a real rubric but is what a rubric will look like! 
:::

Type your answers to these questions in a separate word document and upload that document to Brightspace for evaluation. There is an "answer template" document attached to the Brightspace assignment.

## Can personality predict loneliness? 

Earlier in the semester you took a survey that asked about personality and loneliness. We already analyzed some of the loneliness data in Homework #3, comparing our sample of UVM Psychology student loneliness to the population norms for college students collected in 1996. In this lab, we will revisit these data, this time to see if we can use the Big 5 personality traits to predict loneliness in our sample.

As a reminder, these data came from these sources: 

- [Ten Item Personality Measure (TIPI)](https://gosling.psy.utexas.edu/scales-weve-developed/ten-item-personality-measure-tipi/)

- [UCLA Loneliness Scale (Version 3)](https://sparqtools.org/mobility-measure/ucla-loneliness-scale-version-3/ )


## Exploring our data

Let's load the dataset and see what variables we have to explore: 

```{webr}
#| edit: false
lonely_data <- read.csv("data/personality_loneliness.csv")
head(lonely_data)
```

Our variables are: 

-  `ID`: An identifier for each participant.

- `extraversion`: A measure of how outgoing and sociable a person is.

- `agreeableness`: A measure of how friendly and warm a person is.

- `conscientiousness`: A measure of how diligent and organized a person is.

- `neuroticism`: A measure of emotionally stable a person is. This particular scale is coded so that high values indicate emotional stability, low values indicate neuroticism.

- `openness`: A measure of how open to new experiences and creative a person is.

- `loneliness`: A measure of how lonely a person is.


We will do two analyses with these data. First, we will look for simple correlations between each of the variables. Then we will perform a standard multiple regression to see how well we can predict loneliness from the personality variables. 

## Question 1: Exploring simple correlations

Let's start by looking at the simple correlation between all of these variables. We can do this by creating a correlation matrix using the function `cor()` in R. This function will let us input an entire dataframe, and it will output the correlation of every pair of variables in our dataset: 

Click "Run Code" to see a basic correlation matrix: 

```{webr}
cor(subset(lonely_data, select = -ID)) #the function subset here is helping us to remove the ID column, which we do not include in the correlation table.
```

The output here is called a **correlation matrix**. Notice that it is a table with all variables listed vertically and horizontally. The values in the table are all values of r (Pearson's correlation coefficient). The diagonal indicates that the correlation of every variable with itself is r = 1.00. You will also notice that each value of r is duplicated above and below this diagonal, because in a grid each correlation is repeated twice. 

Some functions in R can create even more elaborate correlation matrices. For example, the function `ggpairs()` from the package `GGally` can create a correlation matrix that shows the correlation below the diagonal, and scatterplots above the diagonal - a lot of information packed into one graphic! 

Click "run code" to see a fancier correlation matrix!

```{webr}
ggpairs(data = subset(lonely_data, select = -ID),
        lower = list(continuous = wrap("smooth", colour="blue", alpha = .2)), 
        diag = list(continuous = "blankDiag"))
```

In this fancier correlation matrix, the diagonal is now blank (to reduce clutter and make the plot easier to read). Above the diagonal we have the Pearson Correlation Coefficient, with asterisks indicating if the relationship is significant (`***` means p < .001). Below the diagonal we have scatterplots to visualize the relationship. 

For Question 1, copy and paste this plot below, then answer the questions about the relationships depicted here. 

### Question 1: Interpreting a correlation matrix
::: {.callout-tip title="Question 1:  Interpreting a correlation matrix"}

Copy and paste the fancy correlation matrix created using the R code above. Then answer the questions listed below about this plot. 

*Rubric for Question 1 (3 points total):*

- **1a (1 point)** Plot is included and is legible & professional (not a screenshot or photo of your entire computer screen) 
- **1b (1 point)** What is the strongest correlation reported in this correlation matrix? Answer by filling in the blanks in this sentence: "The strongest correlation is between _______ and _______, with r = ________". 
- **1c (1 point)** What is the weakest correlation reported in this correlation matrix? Answer by filling in the blanks in this sentence: "The weakest correlation is between _______ and _______, with r = ________". 

:::

## Question 2: Multiple Regression

Next we will use these data to conduct a standard multiple regression. Our output variable will be `loneliness`. As predictor variables we will include all of the Big 5 personality traits (`extraversion`, `agreeableness`, `conscientiousness`, `neuroticism`, and `openness`)

The function that we will use to produce a regression is `lm()` with formula notation to indicate the relationship between our outcome variable and our predictor variables. That is, our outcome variable `loneliness` will go on the left of the `~` symbol, and our predictor variables will go on the right (separated by a `+` sign). 

```{webr}
lonely_model <- lm(data = lonely_data, loneliness ~ extraversion + agreeableness + conscientiousness + neuroticism + openness)
lonely_model
```

Notice that the results of our `lm()` function here show us the coefficients for the intercept and for each predictor. For question 2a, use these values to write out the full regression equation that we could use to predict loneliness (see multiple regression slides for an example!). 


### Question 2a: Writing a regression equation
::: {.callout-tip title="Question 2a: Writing a regression equation"}

Using the output above, write the regression equation by plugging in the correlation coefficients into the blanks below (round to 2 decimals): 

loneliness = _______extraversion + _______agreeableness + _______conscientiousness + _______neuroticism + _______openness + _______. 

*Rubric for Question 2a (2 points total):*

- The regression equation is filled out correctly (fill in the blanks in the example above). Round each coefficient to 2 decimals. **.5 points for each coefficient placed correctly in the regression equation.** 

:::

The output of the linear model gives us all of the coefficients for our regression equation, but that's all the information it gives us. How can we tell our model fit, or whether the model or any individual coefficients are significant? The function `summary()` will give us all of this additional information: 

```{webr}
summary(lonely_model)
```

Use the output above to write up a full write-up of our regression, using the rubric below and slides posted on Brightspace to make sure you are including all needed information. 

### Question 2b: Writing up the results of a regression
::: {.callout-tip title="Question 2b: Writing up the results of a regression"}

Use the summary output of the regression model to write up the results of our regression in APA format. Your write-up should be written in a full paragraph (do not reply in individual bulletpoints to the points below).

*Rubric for Question 2b (5 points total):*
Your write-up should be written in a full paragraph (do not reply in individual bulletpoints to the points below - this is just a checklist for you to make sure you included everything you need. A point will be deducted if your write-up is not written in a professional paragraph).

- (**1 point**):  State whether the overall model was significant, and report F-ratio, df, and p-value in APA format.

- (**1 point**): State how much of the variance in loneliness is explained by our model, and report R-squared. 

- (**3 points**): State the significance of each predictor in the model, reporting b, SE, and p in parentheses for each predictor. 

:::

